#pragma once

#define VOLUME_WIDTH 256
#define VOLUME_HEIGHT 256
#define VOLUME_DEPTH 225
#define VOLUME_SIZE ((VOLUME_WIDTH) * (VOLUME_HEIGHT) * (VOLUME_DEPTH))

#define TEXTURE_WIDTH 256
#define TEXTURE_HEIGHT 256
#define TEXTURE_SIZE ((TEXTURE_WIDTH) * (TEXTURE_HEIGHT) * 3)

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 800

#define STEP 1.f
